Repository Workiva/json_schema, pull requests merged in 2018-04, with the labels that each got.

#12 EPL-8414 feat(package): support JSON Schema draft6
  lib/json_schema.dart
  lib/src/json_schema/browser/platform_functions.dart
  lib/src/json_schema/constants.dart
  lib/src/json_schema/format_exceptions.dart
  lib/src/json_schema/json_schema.dart
  lib/src/json_schema/type_validators.dart
  lib/src/json_schema/typedefs.dart
  lib/src/json_schema/utils.dart
  lib/src/json_schema/validator.dart
  lib/src/json_schema/vm/platform_functions.dart
  pubspec.yaml
  test/invalid_schemas/draft4/additionalProperties.json
  test/invalid_schemas/draft4/allOf.json
  test/invalid_schemas/draft4/anyOf.json
  test/invalid_schemas/draft4/cycle.json
  test/invalid_schemas/draft4/definitions.json
  test/invalid_schemas/draft4/dependencies.json
  test/invalid_schemas/draft4/description.json
  test/invalid_schemas/draft4/enum.json
  test/invalid_schemas/draft4/exclusiveMaximum.json
  test/invalid_schemas/draft4/exclusiveMinimum.json
  test/invalid_schemas/draft4/freeFormProperty.json
  test/invalid_schemas/draft4/id.json
  test/invalid_schemas/draft4/items.json
  test/invalid_schemas/draft4/maxLength.json
  test/invalid_schemas/draft4/maxProperties.json
  test/invalid_schemas/draft4/maximum.json
  test/invalid_schemas/draft4/minItems.json
  test/invalid_schemas/draft4/minLength.json
  test/invalid_schemas/draft4/minProperties.json
  test/invalid_schemas/draft4/minimum.json
  test/invalid_schemas/draft4/multipleOf.json
  test/invalid_schemas/draft4/not.json
  test/invalid_schemas/draft4/oneOf.json
  test/invalid_schemas/draft4/pattern.json
  test/invalid_schemas/draft4/patternProperties.json
  test/invalid_schemas/draft4/properties.json
  test/invalid_schemas/draft4/ref.json
  test/invalid_schemas/draft4/required.json
  test/invalid_schemas/draft4/title.json
  test/invalid_schemas/draft4/type.json
  test/invalid_schemas/draft4/uniqueItems.json
  test/unit/vm/json_schema/invalid_schemas_test.dart
  test/unit/vm/json_schema/validation_test.dart
Labels: semver: Major

#14 Update Dockerfile to Mirror smithy.yaml
  Dockerfile
Labels: semver: Patch

#10 BUILDTOOLS-2329: Update Dockerfile to mirror smithy.yaml
  Dockerfile
Labels: Merge Requirements Met, semver: Patch
