Repository Workiva/json_schema, pull requests merged in 2018-07, with the labels that each got.

#22 fix a Completer's type
  lib/src/json_schema/schema.dart
Labels: Merge Requirements Unmet

#20 EPL-8486: Allow Consumers to Specify a Custom $ref Resolver
  lib/json_schema.dart
  lib/src/json_schema/json_schema.dart
  lib/src/json_schema/typedefs.dart
  test/unit/vm/json_schema/validation_test.dart
Labels: semver: Minor

#23 EPL-6673 Release json_schema 1.0.9
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, semver: Error

#24 EPL-9827 Release json_schema 2.0.0-RC1
  pubspec.yaml
Labels: Merge Requirements Unmet, RM Ready, semver: Major

#27 fix constants for dart 1 and dart 2 compat based off 1.0.9
  bin/schemadot.dart
  example/from_url/validate_instance_from_url.dart
  lib/json_schema.dart
  lib/src/json_schema/schema.dart
  pubspec.yaml
  test/unit/vm/json_schema/invalid_schemas_test.dart
  test/unit/vm/json_schema/validation_test.dart
Labels: semver: Patch

#26 Make compatible with Dart 1 and Dart 2 constant names
  bin/schemadot.dart
  example/from_url/validate_instance_from_url.dart
  lib/src/json_schema/constants.dart
  lib/src/json_schema/json_schema.dart
  lib/src/json_schema/vm/platform_functions.dart
  pubspec.yaml
  test/unit/vm/json_schema/invalid_schemas_test.dart
  test/unit/vm/json_schema/validation_test.dart
Labels: Merge Requirements Unmet, RM Ready

#28 EPL-9829 Release json_schema 2.0.0-RC2
  pubspec.yaml
Labels: Merge Requirements Unmet, RM Ready, semver: Patch
