Repository Workiva/json_schema, pull requests merged in 2019-02, with the labels that each got.

#39 CPLAT-4192: Update json_schema to be Dart 2 compatible
  .travis.yml
  Dockerfile
  analysis_options.yaml
  lib/src/json_schema/json_schema.dart
  lib/src/json_schema/utils.dart
  pubspec.yaml
  test/unit/vm/json_schema/validation_test.dart
  tool/dev.dart
Labels: Hold Auto-Merge, Merge Requirements Met, RM Ready, semver: Patch

#40 WAP-1552 Release json_schema 2.0.1
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, semver: Patch

#41 WAP-2264: Convenience getters around property names and required properties
  lib/src/json_schema/json_schema.dart
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, semver: Minor

#42 WAP-2350 Release json_schema 2.1.0
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready, semver: Minor
