Repository Workiva/json_schema, pull requests merged in 2022-01, with the labels that each got.

#94 imp(validator): expose two errors for missing properties, one for the root object path, as well as the property itself
  lib/src/json_schema/validator.dart
  test/unit/json_schema/validation_error_test.dart
Labels: Merge Requirements Met, RM Ready

#96 Implement minContains and maxContains for draft 2019-09
  lib/src/json_schema/json_schema.dart
  lib/src/json_schema/validator.dart
  test/unit/constants.dart
Labels: Merge Requirements Met

#95 Implement support for deprecated keyword
  example/from_json/movie_sample.dart
  lib/src/json_schema/json_schema.dart
  lib/src/json_schema/validator.dart
Labels: Merge Requirements Met

#97 Add basic untested $defs
  lib/src/json_schema/json_schema.dart
Labels: Merge Requirements Met

#102 Implement $contentSchema, $contentEncoding Keywords
  lib/src/json_schema/json_schema.dart
Labels: Merge Requirements Unmet

#98 Mixing JsonSchema objects to support properties along side of $refs
  lib/src/json_schema/json_schema.dart
  lib/src/json_schema/utils.dart
  lib/src/json_schema/validator.dart
  test/unit/constants.dart
  test/unit/json_schema/specification_test.dart
  test/unit/json_schema/validation_error_test.dart
Labels: Merge Requirements Met

#100 Anchor support
  lib/src/json_schema/constants.dart
  lib/src/json_schema/json_schema.dart
  lib/src/json_schema/type_validators.dart
  lib/src/json_schema/validator.dart
  test/unit/constants.dart
Labels: Merge Requirements Met

#104 Implement Dependent Schemas and Requiremets
  lib/src/json_schema/json_schema.dart
  test/unit/constants.dart
Labels: Merge Requirements Unmet

#101 Inline the Draft2019-09 subschema definitions
  lib/src/json_schema/constants.dart
  lib/src/json_schema/json_schema.dart
  test/unit/constants.dart
Labels: Merge Requirements Unmet

#108 Clean up and characterize skipped test files
  test/unit/constants.dart
Labels: Merge Requirements Met

#109 Update to latest JSON-Schema-Test-Suite
  test/JSON-Schema-Test-Suite/README.md
  test/JSON-Schema-Test-Suite/bin/jsonschema_suite
  test/JSON-Schema-Test-Suite/remotes/draft-next/format-assertion-false.json
  test/JSON-Schema-Test-Suite/remotes/draft-next/format-assertion-true.json
  test/JSON-Schema-Test-Suite/remotes/draft-next/metaschema-no-validation.json
  test/JSON-Schema-Test-Suite/tests/draft-next/optional/format-assertion.json
  test/JSON-Schema-Test-Suite/tests/draft-next/vocabulary.json
  test/JSON-Schema-Test-Suite/tests/draft2019-09/optional/format/unknown.json
  test/JSON-Schema-Test-Suite/tests/draft2020-12/optional/format/unknown.json
  test/JSON-Schema-Test-Suite/tests/draft4/optional/format/unknown.json
  test/JSON-Schema-Test-Suite/tests/draft6/contains.json
  test/JSON-Schema-Test-Suite/tests/draft6/optional/format/unknown.json
  test/JSON-Schema-Test-Suite/tests/draft7/optional/format/unknown.json
  test/unit/specification_remotes.dart
  test/unit/specification_tests.dart
Labels: Merge Requirements Met, RM Ready

#107 Ignore Old Keywords $definitions and $dependencies
  lib/src/json_schema/json_schema.dart
Labels: Merge Requirements Met

#113 RM-124999 Release json_schema 3.1.0
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#110 Switch subschema inlining to use $defs
  lib/src/json_schema/constants.dart
Labels: Merge Requirements Met

#105 Implement unevaluatedItems
  lib/src/json_schema/json_schema.dart
  lib/src/json_schema/validator.dart
  test/unit/constants.dart
Labels: Merge Requirements Met

#114 chore(package): downgrade http dep
  pubspec.yaml
  tool/cors_headers.dart
  tool/serve_remotes.dart
Labels: Merge Requirements Met, RM Ready, Security Review Required

#116 RM-130662 Release json_schema 3.1.1
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#106 Implement $vocabulary Support
  lib/src/json_schema/constants.dart
  lib/src/json_schema/json_schema.dart
  lib/src/json_schema/validator.dart
  test/unit/constants.dart
Labels: Merge Requirements Met

#111 Implementation for unevaluated properties.
  lib/src/json_schema/json_schema.dart
  lib/src/json_schema/validator.dart
  test/unit/constants.dart
Labels: Merge Requirements Met

#119 Add validateWithResults, Deprecate Preexisting
  example/from_json/movie_sample.dart
  example/from_json/validate_json_from_data.dart
  example/from_url/validate_instance_from_url.dart
  example/readme/asynchronous_creation/from_file.dart
  example/readme/asynchronous_creation/from_url.dart
  example/readme/asynchronous_creation/remote_http_refs.dart
  example/readme/asynchronous_creation/remote_ref_cache.dart
  example/readme/synchronous_creation/local_ref_cache.dart
  example/readme/synchronous_creation/self_contained.dart
  lib/src/json_schema/json_schema.dart
  lib/src/json_schema/validator.dart
  test/unit/json_schema/configurable_format_validation_test.dart
  test/unit/json_schema/nested_refs_in_root_schema_test.dart
  test/unit/json_schema/relative_file_uri_test.dart
  test/unit/json_schema/schema_self_validation.dart
  test/unit/json_schema/validation_error_test.dart
Labels: Merge Requirements Met, RM Ready

#122 RM-130782 Release json_schema 3.2.0
  CHANGELOG.md
  pubspec.yaml
Labels: Merge Requirements Met, RM Ready

#115 Make it very easy to add custom json schema tests.
  test/custom/invalid_schemas/draft4/additionalProperties.json
  test/custom/invalid_schemas/draft4/allOf.json
  test/custom/invalid_schemas/draft4/anyOf.json
  test/custom/invalid_schemas/draft4/cycle.json
  test/custom/invalid_schemas/draft4/definitions.json
  test/custom/invalid_schemas/draft4/dependencies.json
  test/custom/invalid_schemas/draft4/description.json
  test/custom/invalid_schemas/draft4/enum.json
  test/custom/invalid_schemas/draft4/exclusiveMaximum.json
  test/custom/invalid_schemas/draft4/exclusiveMinimum.json
  test/custom/invalid_schemas/draft4/freeFormProperty.json
  test/custom/invalid_schemas/draft4/id.json
  test/custom/invalid_schemas/draft4/items.json
  test/custom/invalid_schemas/draft4/maxLength.json
  test/custom/invalid_schemas/draft4/maxProperties.json
  test/custom/invalid_schemas/draft4/maximum.json
  test/custom/invalid_schemas/draft4/minItems.json
  test/custom/invalid_schemas/draft4/minLength.json
  test/custom/invalid_schemas/draft4/minProperties.json
  test/custom/invalid_schemas/draft4/minimum.json
  test/custom/invalid_schemas/draft4/multipleOf.json
  test/custom/invalid_schemas/draft4/not.json
  test/custom/invalid_schemas/draft4/oneOf.json
  test/custom/invalid_schemas/draft4/pattern.json
  test/custom/invalid_schemas/draft4/patternProperties.json
  test/custom/invalid_schemas/draft4/properties.json
  test/custom/invalid_schemas/draft4/ref.json
  test/custom/invalid_schemas/draft4/required.json
  test/custom/invalid_schemas/draft4/title.json
  test/custom/invalid_schemas/draft4/type.json
  test/custom/invalid_schemas/draft4/uniqueItems.json
  test/custom/valid_schemas/draft2019-09/example.json
  test/unit/json_schema/draft4_invalid_schemas_test.dart
  test/unit/specification_tests.dart
  tool/gen.dart
Labels: Merge Requirements Met

#112 Different dynamic parent for refs.
  lib/src/json_schema/json_schema.dart
  lib/src/json_schema/utils.dart
  lib/src/json_schema/validator.dart
  test/unit/constants.dart
  test/unit/json_schema/specification_test.dart
Labels: Merge Requirements Met
